/* ════════════════════════════════════
   data.js  —  All application data
   ════════════════════════════════════ */

const BOOKS = [
  { id:1,  title:"Dune",                             author:"Frank Herbert",        genre:"Science Fiction", emoji:"🪐", colors:["#6b3fa0","#2e0f6a"], rating:4.9, ratingCount:24832, pages:688,  reads:"4.2M",  votes:"312K", aiPick:true,  tags:["Sci-Fi","Epic","Classic"],          year:1965, desc:"A stunning tale of politics, religion, and survival on the desert planet Arrakis. One of the greatest science fiction novels ever written.",                                              chapter:"Arrakis — Desert Planet",               text:"A beginning is the time for taking the most delicate care that the balances are correct. To begin your study of the life of Muad'Dib, take care that you first place him in his time: born in the 57th year of the Padishah Emperor, Shaddam IV.\n\nThe boy's mother, the Lady Jessica, was a Bene Gesserit and a concubine of the Duke Leto Atreides — considered one of the most able leaders in the Imperium.\n\nArrakis. Dune. Desert Planet. The source of the spice melange, most valuable substance in the universe. The planet where the Fremen wait. The planet whose winds carry the seeds of the future." },
  { id:2,  title:"Atomic Habits",                    author:"James Clear",           genre:"Non-Fiction",     emoji:"⚛️", colors:["#1a6b3a","#073020"], rating:4.8, ratingCount:19201, pages:320,  reads:"3.1M",  votes:"241K", aiPick:true,  tags:["Self-Help","Productivity"],         year:2018, desc:"Tiny changes, remarkable results. An easy and proven way to build good habits and break bad ones forever.",                                                                              chapter:"The Surprising Power of Tiny Gains",    text:"If you can get 1 percent better each day for one year, you'll end up thirty-seven times better by the time you're done.\n\nWhat starts as a small win accumulates into something much more. Habits are the compound interest of self-improvement — they seem to make little difference on any given day, yet the impact they deliver over months and years can be enormous.\n\nThe effects only become visible once you cross a critical threshold — a point at which you reap the rewards of all your previous work." },
  { id:3,  title:"The Great Gatsby",                 author:"F. Scott Fitzgerald",   genre:"Romance",         emoji:"🍸", colors:["#1a5a8a","#071e3d"], rating:4.5, ratingCount:31044, pages:180,  reads:"6.8M",  votes:"521K", aiPick:false, tags:["Classic","Romance","American"],     year:1925, desc:"A portrait of the Jazz Age — Jay Gatsby's obsession with a lost love told through the eyes of Nick Carraway with breathtaking beauty.",                                                  chapter:"Chapter One",                           text:"In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since.\n\n'Whenever you feel like criticizing anyone,' he told me, 'just remember that all the people in this world haven't had the advantages that you've had.'\n\nHe didn't say any more, but we've always been unusually communicative in a reserved way, and I understood that he meant a great deal more than that. In consequence, I'm inclined to reserve all judgements." },
  { id:4,  title:"Sapiens",                          author:"Yuval Noah Harari",     genre:"Non-Fiction",     emoji:"🦴", colors:["#8a5a10","#3a2000"], rating:4.7, ratingCount:22187, pages:512,  reads:"2.9M",  votes:"198K", aiPick:true,  tags:["History","Philosophy","Science"],   year:2011, desc:"A brief history of humankind — from the Stone Age to the present. How biology and history have defined us and what our future may hold.",                                                 chapter:"An Animal of No Significance",          text:"About 13.5 billion years ago, matter, energy, time and space came into being in the Big Bang.\n\nAbout 300,000 years after their appearance, matter and energy started to coalesce into complex structures called atoms, which then combined into molecules. The story of atoms, molecules and their interactions is called chemistry.\n\nAbout 3.8 billion years ago on a planet called Earth, certain molecules combined to form particularly large and intricate structures called organisms. The story of organisms is called biology." },
  { id:5,  title:"The Hobbit",                       author:"J.R.R. Tolkien",        genre:"Fantasy",         emoji:"🏔️", colors:["#2a6a18","#0a2a05"], rating:4.9, ratingCount:41022, pages:310,  reads:"8.4M",  votes:"673K", aiPick:false, tags:["Fantasy","Adventure","Classic"],    year:1937, desc:"Bilbo Baggins, a perfectly respectable hobbit, is swept into an epic quest with thirteen dwarves and the wizard Gandalf to reclaim a dragon-guarded treasure.",                           chapter:"An Unexpected Party",                   text:"In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.\n\nIt had a perfectly round door like a porthole, painted green, with a shiny yellow brass knob in the exact middle. The door opened on to a tube-shaped hall like a tunnel — a very comfortable tunnel without smoke, with panelled walls, and floors tiled and carpeted." },
  { id:6,  title:"1984",                             author:"George Orwell",         genre:"Mystery",         emoji:"👁️", colors:["#3a3a4a","#10101a"], rating:4.8, ratingCount:38201, pages:328,  reads:"7.2M",  votes:"584K", aiPick:false, tags:["Dystopia","Classic","Political"],   year:1949, desc:"A chilling vision of a totalitarian future where Big Brother watches every move and thought crime is punishable by death.",                                                               chapter:"Part One",                              text:"It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind, slipped quickly through the glass doors of Victory Mansions.\n\nThe hallway smelt of boiled cabbage and old rag mats. At one end of it a coloured poster, too large for indoor display, had been tacked to the wall. It depicted simply an enormous face — more than a metre wide — the face of a man of about forty-five, with a heavy black moustache." },
  { id:7,  title:"It Ends with Us",                  author:"Colleen Hoover",        genre:"Romance",         emoji:"💐", colors:["#8a2060","#3a0025"], rating:4.7, ratingCount:52841, pages:368,  reads:"14.6M", votes:"1.1M", aiPick:true,  tags:["Romance","Drama","Teen Fiction"],   year:2016, desc:"A brave and heartbreaking novel that asks: what happens when the love you thought would save you is the love that destroys you?",                                                        chapter:"Chapter One",                           text:"I have lived in this town my entire life, yet tonight feels different. The air is thick with possibility and the kind of restlessness that makes your heart beat just a little faster.\n\nI'm twenty-two years old, fresh out of college, and sitting on the roof of a building that isn't mine. But the view of the city from up here makes it worth the risk.\n\nSometimes you just need to look at things from a different angle. Whether it's the roof of a building or the pages of a book, perspective is everything." },
  { id:8,  title:"Harry Potter & The Sorcerer's Stone", author:"J.K. Rowling",      genre:"Fantasy",         emoji:"⚡", colors:["#7a2a0a","#2a0800"], rating:4.9, ratingCount:91033, pages:309,  reads:"22.4M", votes:"1.8M", aiPick:false, tags:["Fantasy","Adventure","Teen Fiction"], year:1997, desc:"On his eleventh birthday, Harry Potter discovers he is a wizard and is accepted into Hogwarts School of Witchcraft and Wizardry.",                                                       chapter:"The Boy Who Lived",                     text:"Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you'd expect to be involved in anything strange or mysterious, because they just didn't hold with such nonsense.\n\nMr. Dursley was the director of a firm called Grunnings, which made drills. He was a big, beefy man with hardly any neck, although he had a very large mustache. Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck." },
  { id:9,  title:"The Night Circus",                 author:"Erin Morgenstern",      genre:"Fantasy",         emoji:"🎪", colors:["#1a1a2a","#2a2a4a"], rating:4.6, ratingCount:18922, pages:387,  reads:"5.3M",  votes:"421K", aiPick:true,  tags:["Fantasy","Romance","Mystery"],      year:2011, desc:"A mysterious circus arrives without warning, only to vanish by morning. Two young magicians compete in a contest whose rules are never explained.",                                       chapter:"Anticipation",                          text:"The circus arrives without warning. No announcements precede it, no paper notices plastered on lampposts and billboards. It is simply there, when yesterday it was not.\n\nWithin the grey-and-white striped tents is an utterly unique experience full of breathtaking amazements. It is called Le Cirque des Rêves, and it is only open at night.\n\nBeyond the gates, just past the ticket booth, is a small placard. It reads simply: 'Not all those who wander are lost.'" },
  { id:10, title:"Pride and Prejudice",              author:"Jane Austen",           genre:"Romance",         emoji:"🌹", colors:["#7a2a5a","#300a25"], rating:4.8, ratingCount:44102, pages:432,  reads:"11.2M", votes:"892K", aiPick:false, tags:["Romance","Classic","Historical"],   year:1813, desc:"The beloved story of Elizabeth Bennet and Mr. Darcy — a witty, irresistible tale of love, misunderstanding, and the need to overcome one's own pride.",                                  chapter:"Chapter One",                           text:"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.\n\nHowever little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters.\n\n'My dear Mr. Bennet,' said his lady to him one day, 'have you heard that Netherfield Park is let at last?'" },
  { id:11, title:"The Alchemist",                    author:"Paulo Coelho",          genre:"Fantasy",         emoji:"✨", colors:["#8a6010","#3a2800"], rating:4.7, ratingCount:35821, pages:208,  reads:"9.1M",  votes:"712K", aiPick:true,  tags:["Fiction","Inspirational","Journey"], year:1988, desc:"Santiago, a young shepherd, discovers his Personal Legend on an extraordinary journey that takes him across continents in search of treasure.",                                           chapter:"Prologue",                              text:"The Alchemist picked up a book that someone in the caravan had brought. Leafing through the pages, he found a story about Narcissus.\n\nHe knew the story of Narcissus: a youth who daily knelt beside a lake to contemplate his own beauty. He was so fascinated by himself that, one morning, he fell into the lake and drowned. At the spot where he fell, a flower was born, which was called the narcissus.\n\nBut this was not how the author of the book ended the story." },
  { id:12, title:"Thinking, Fast and Slow",          author:"Daniel Kahneman",       genre:"Non-Fiction",     emoji:"🧠", colors:["#5a208a","#200840"], rating:4.6, ratingCount:16201, pages:499,  reads:"1.8M",  votes:"142K", aiPick:true,  tags:["Psychology","Science","Self-Help"],  year:2011, desc:"A groundbreaking tour of the two systems that drive the way we think — fast, intuitive System 1 and slow, deliberate System 2.",                                                        chapter:"The Characters of the Story",           text:"The premise of this book is that it is easier to recognize other people's mistakes than our own. I describe many experiments that reveal how we often make mistakes in thinking.\n\nThese are not just logical errors; they are systematic biases that affect our judgments and decisions in predictable ways.\n\nThe goal of this book is to improve the ability to identify and understand mistakes of judgement and choice, in others and eventually in ourselves — by providing a richer and more precise language to discuss them." },
  { id:13, title:"Man's Search for Meaning",         author:"Viktor E. Frankl",      genre:"Non-Fiction",     emoji:"🕯️", colors:["#4a3a2a","#1a100a"], rating:4.9, ratingCount:29018, pages:200,  reads:"3.7M",  votes:"289K", aiPick:true,  tags:["Philosophy","Psychology","Memoir"],  year:1946, desc:"A psychiatrist's memoir of surviving Nazi death camps, and his method of finding meaning and purpose even in the darkest of circumstances.",                                            chapter:"Experiences in a Concentration Camp",   text:"We who lived in concentration camps can remember the men who walked through the huts comforting others, giving away their last piece of bread.\n\nThey may have been few in number, but they offer sufficient proof that everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances, to choose one's own way.\n\nAnd there were always choices to make. Every day, every hour, offered the opportunity to make a decision." },
  { id:14, title:"A Brief History of Time",          author:"Stephen Hawking",       genre:"Non-Fiction",     emoji:"🌌", colors:["#0a1a4a","#050a20"], rating:4.6, ratingCount:22018, pages:212,  reads:"2.3M",  votes:"178K", aiPick:false, tags:["Science","Physics","Classic"],       year:1988, desc:"One of the most accessible explorations of cosmology — from the Big Bang to black holes — by the legendary physicist.",                                                                  chapter:"Our Picture of the Universe",           text:"A well-known scientist once gave a public lecture on astronomy. He described how the earth orbits around the sun and how the sun, in turn, orbits around the center of a vast collection of stars called our galaxy.\n\nAt the end of the lecture, a little old lady at the back of the room got up and said: 'What you have told us is rubbish. The world is really a flat plate supported on the back of a giant tortoise.'\n\n'What is the tortoise standing on?' the scientist asked. 'It's turtles all the way down!' replied the old lady." },
  { id:15, title:"Divergent",                        author:"Veronica Roth",         genre:"Teen Fiction",    emoji:"🔮", colors:["#1a4a6a","#070d20"], rating:4.5, ratingCount:48201, pages:487,  reads:"12.1M", votes:"980K", aiPick:false, tags:["Teen Fiction","Dystopia","Adventure"], year:2011, desc:"In a future Chicago divided into five factions, Beatrice discovers a secret that could destroy everything she knows.",                                                                    chapter:"Chapter One",                           text:"There is one mirror in my house. It is behind a sliding panel in the hallway upstairs. My mother calls it an indulgence.\n\nWhen the panel is open, I stand in the doorway and stare at myself: blond hair, blue-gray eyes, nose that turns up at the end, narrow shoulders. I wonder, as I have every morning for the past three years, if I will have the same face and body when I am forty as I do now at sixteen.\n\nI can see why she would call it an indulgence." },
  { id:16, title:"The Shadow of the Wind",           author:"Carlos Ruiz Zafón",     genre:"Mystery",         emoji:"📚", colors:["#2a1a4a","#0d0520"], rating:4.7, ratingCount:17809, pages:487,  reads:"3.4M",  votes:"267K", aiPick:true,  tags:["Mystery","Historical","Romance"],    year:2001, desc:"A young boy discovers a mysterious novel in a hidden library in post-war Barcelona and becomes entangled in a deadly web of secrets.",                                                    chapter:"The Cemetery of Forgotten Books",       text:"I still remember the day my father took me to the Cemetery of Forgotten Books for the first time. It was the early summer of 1945, and we walked through the streets of a Barcelona trapped beneath ashen skies as dawn poured over Rambla de Santa Monica in a wreath of liquid copper.\n\n'Daniel, you mustn't tell anyone what you're about to see today,' my father warned. 'Not your school friends, not anybody.'\n\nFollowing my father through the arched doorway, I felt as though I were entering another world." },
];

const READING = [
  { id:7,  pct:72, lastRead:"2 hours ago"  },
  { id:5,  pct:35, lastRead:"Yesterday"    },
  { id:15, pct:88, lastRead:"3 days ago"   },
];

const LIBRARY_IDS = [1, 3, 6, 10, 11, 16];

const GENRES = [
  { name:"Romance",         icon:"💕", count:"12.4M" },
  { name:"Fantasy",         icon:"🐉", count:"8.7M"  },
  { name:"Science Fiction", icon:"🚀", count:"5.2M"  },
  { name:"Mystery",         icon:"🔎", count:"6.1M"  },
  { name:"Horror",          icon:"👻", count:"3.8M"  },
  { name:"Non-Fiction",     icon:"📖", count:"4.3M"  },
  { name:"Historical",      icon:"🏛️", count:"2.9M"  },
  { name:"Teen Fiction",    icon:"🌟", count:"9.1M"  },
  { name:"Adventure",       icon:"⚔️", count:"4.6M"  },
  { name:"Poetry",          icon:"🎵", count:"1.8M"  },
  { name:"Humor",           icon:"😂", count:"2.4M"  },
  { name:"Short Story",     icon:"📝", count:"7.2M"  },
];

const COMMUNITIES = [
  { id:"romance",  name:"Romance Readers",   desc:"Swoon-worthy moments, book boyfriends, love stories.",         emoji:"💕", members:"2.4M", joined:false },
  { id:"fantasy",  name:"Fantasy & Sci-Fi",  desc:"World-building, magic systems, and everything beyond.",        emoji:"🐉", members:"1.8M", joined:true  },
  { id:"teen",     name:"Teen Fiction Hub",  desc:"Young adult fiction, school drama, coming-of-age stories.",    emoji:"🌟", members:"3.1M", joined:false },
  { id:"horror",   name:"Horror & Thriller", desc:"All things dark, suspenseful, and terrifying.",                emoji:"👻", members:"720K", joined:false },
  { id:"classics", name:"Classic Literature",desc:"Deep dives into timeless works by the greatest authors.",      emoji:"📜", members:"540K", joined:true  },
  { id:"nonfic",   name:"Non-Fiction Club",  desc:"Science, history, philosophy, self-help — real stories.",      emoji:"📖", members:"890K", joined:false },
];

const USER = {
  name: "Arjun Kumar",
  handle: "@arjunkumar",
  avatar: "AK",
  joinedYear: 2024,
  prefs: ["Romance","Fantasy","Sci-Fi","Mystery","Thriller","Non-Fiction"],
};

const ACTIVITY = {
  months: ["Oct","Nov","Dec","Jan","Feb","Mar"],
  values: [3, 5, 2, 8, 6, 4]
};

// Seed reviews per book
const REVIEWS_DATA = {
  1: [
    { user:"Maya R", avatar:"MR", stars:5, text:"Absolutely breathtaking world-building. Dune is unlike anything else in science fiction. Read it twice.", date:"2 weeks ago", helpful:42 },
    { user:"James T", avatar:"JT", stars:4, text:"Dense but rewarding. The political intrigue is fascinating. Takes patience but worth every page.", date:"1 month ago", helpful:28 },
  ],
  5: [
    { user:"Sofia L", avatar:"SL", stars:5, text:"The perfect adventure! Cozy, epic, and heartwarming all at once. Tolkien is a master storyteller.", date:"3 days ago", helpful:15 },
  ],
  7: [
    { user:"Priya S", avatar:"PS", stars:5, text:"I cried so much. Colleen Hoover writes emotions like no one else. This book will stay with me forever.", date:"1 week ago", helpful:67 },
    { user:"Tom K", avatar:"TK", stars:4, text:"Powerful and raw. Not what I expected but completely captivating. Warning: have tissues ready.", date:"2 months ago", helpful:33 },
  ],
  8: [
    { user:"Aisha M", avatar:"AM", stars:5, text:"Still magical after all these years. The world of Hogwarts never gets old. Perfect for all ages.", date:"5 days ago", helpful:89 },
  ],
};

const AI_REPLIES = {
  romance:   "Love it! Try **It Ends with Us** (Hoover), **Pride and Prejudice** (Austen), and **The Hating Game** (Thorne). Your heart won't know what hit it 💕",
  fantasy:   "Perfect choice! **The Night Circus** (Morgenstern), **Mistborn** (Sanderson), and **The Name of the Wind** (Rothfuss). Pure magic on every page 🐉",
  horror:    "Ooh scary! **The Shining** (King), **Mexican Gothic** (Moreno-Garcia), **House of Leaves** (Danielewski). Prepare for sleepless nights 👻",
  "sci-fi":  "Epic taste! **Dune** (Herbert), **Project Hail Mary** (Weir), **Foundation** (Asimov). Mind-bending reads 🚀",
  mystery:   "Love mysteries! **Gone Girl** (Flynn), **The Girl with the Dragon Tattoo** (Larsson), **Big Little Lies** (Moriarty). Impossible to put down 🔎",
  harry:     "If you loved Harry Potter, try **Percy Jackson** (Riordan), **The Magicians** (Grossman), and **A Deadly Education** (Novik) ⚡",
  dune:      "Dune fans love **Foundation** (Asimov), **Hyperion** (Simmons), and **The Left Hand of Darkness** (Le Guin) 🪐",
  sad:       "Need a cry? **The Fault in Our Stars** (Green), **Me Before You** (Moyes), **A Little Life** (Yanagihara) 😭",
  funny:     "Laugh out loud with **Good Omens** (Gaiman & Pratchett), **The Hitchhiker's Guide** (Adams), **Catch-22** (Heller) 😂",
  history:   "Great picks: **Sapiens** (Harari), **The Silk Roads** (Frankopan), **Guns, Germs and Steel** (Diamond) 🏛️",
  classic:   "Must-reads: **Pride and Prejudice** (Austen), **1984** (Orwell), **The Great Gatsby** (Fitzgerald). Timeless! 📜",
  default: [
    "Based on your reading history, I'd love to recommend **The Night Circus** by Erin Morgenstern — absolutely unputdownable! Also try **Project Hail Mary** by Andy Weir 📚",
    "Your profile shows you love complex stories! Try **The Shadow of the Wind** (Zafón), **All the Light We Cannot See** (Doerr), and **The Book Thief** (Zusak) ✨",
    "Here are 3 picks tailored just for you:\n📚 **It Ends with Us** — emotional masterpiece\n📚 **The Way of Kings** — epic fantasy\n📚 **Educated** by Tara Westover — stunning memoir",
  ],
};
